#!/bin/sh
project_dir_name=integratoredu
flag_name=app.js
if [ -f $flag_name ]; then
  # echo "detected $flag_name"
  echo
elif [ -d ~/Applications/$project_dir_name ]; then
  cd ~/Applications/$project_dir_name
elif [ -d ~/GitHub/$project_dir_name ]; then
  cd ~/GitHub/$project_dir_name
elif [ -d ~/Documents/GitHub/$project_dir_name ]; then
  cd ~/Documents/GitHub/$project_dir_name
elif [ -d ~/git/$project_dir_name ]; then
  cd ~/git/$project_dir_name
elif [ -d ../../$project_dir_name ]; then
  cd ../../$project_dir_name
elif [ -d ../$project_dir_name ]; then
  cd ../$project_dir_name
else
  echo "WARNING in noscreen: could not find $project_dir_name,"
  echo "  so using current directory."
fi

if [ -f /usr/bin/node ]; then
  node app.js
else
  js app.js
fi
