#!/bin/sh
if [ -d ~/Applications/integratoredu ]; then
  cd ~/Applications/integratoredu
else
  if [ -d ~/GitHub/integratoredu ]; then
    cd ~/GitHub/integratoredu
  else
    cd ~/Documents/GitHub/integratoredu
  fi
fi

if [ -f /usr/bin/node ]; then
  node app.js
else
  js app.js
fi
