#!/bin/sh
if [ -d ~/Applications/integratoredu ]; then
  cd ~/Applications/integratoredu
else
  cd ~/Documents/GitHub/integratoredu
fi

if [ -f /usr/bin/node ]; then
  node app.js
else
  js app.js
fi
