#!/bin/sh
#BROKEN: screen -t MinetestServer minetestserver --gameid minetest_next --draworigin --drawplayers --world FCAWorldMTNext
#BROKEN: screen -t MinetestServer minetestserver --gameid ENLIVEN --worldname FCAGameAWorld
#NOTE: if only title is set, screen -x must be used to resume, so use -S <name> to resume with -r <name>
#screen -S MinetestServer minetestserver --gameid ENLIVEN --worldname FCAGameAWorld
#screen -S MinetestServer /home/owner/minetest/bin/minetestserver --gameid ENLIVEN --worldname FCAGameAWorld
project_dir_name=integratoredu
if [ -d ~/Applications/$project_dir_name ]; then
  cd ~/Applications/$project_dir_name
elif [ -d ~/Documents/GitHub/$project_dir_name ]; then
  cd ~/Documents/GitHub/$project_dir_name
elif [ -d ~/GitHub/$project_dir_name ]; then
  cd ~/GitHub/$project_dir_name
elif [ -d ~/git/$project_dir_name ]; then
  cd ~/git/$project_dir_name
elif [ -d ../$project_dir_name ]; then
  cd ../$project_dir_name
elif [ -d ../../$project_dir_name ]; then
  cd ../../$project_dir_name
else
  echo "WARNING: could not find integratoredu, so trying current directory (`pwd`)"
fi

if [ -f app.js ]; then
  #js app.js
  if [ `which screen` ]; then
    if [ -f /usr/bin/node ]; then
      screen -S integratoredu node app.js
    else
      screen -S integratoredu js app.js
    fi
  else
    echo "The screen package is not installed. Try running noscreen script (or just run app.js directly using node) instead."
  fi
else
  echo "missing app.js--try altering this script to change to the correct directory"
fi
